### ISSUE TITLE
SyntaxError: invalid syntax when running

### ISSUE THREAD

**Issue by DinisCruz** [avatao-content/challenge-toolbox#10]
here is the error I got when executing ```$python ./build.py templates/xss```:

```
Traceback (most recent call last):
  File "./build.py", line 9, in <module>
    from common import get_sys_args, yield_dockerfiles
  File "/Users/diniscruz/_Dev_Tests/avatao/challenge-toolbox/common.py", line 14
    def find_repo_path(base: str) -> str:
                           ^
SyntaxError: invalid syntax
```

**Comment by DinisCruz** [comment]
The solution is to use ```python3```, then it works

```
[DEBUG] Running docker build -t eu.gcr.io/avatao-challengestore/xss:controller -f /Users/diniscruz/_Dev_Tests/avatao/challenge-toolbox/templates/xss/controller/Dockerfile /Users/diniscruz/_Dev_Tests/avatao/challenge-toolbox/templates/xss ...
Sending build context to Docker daemon 379.4 kB
Step 1/6 : FROM avatao/xss-controller:ubuntu-16.04
ubuntu-16.04: Pulling from avatao/xss-controller
75c416ea735c: Pull complete 
c6ff40b6d658: Pull complete 
a7050fc1f338: Pull complete 
f0ffb5cf6ba9: Pull complete 
be232718519c: Pull complete 
351278ca44aa: Pull complete 
5cf0c452e30f: Pull complete 
ca84d6cea2c7: Pull complete 
90c3df25b65a: Pull complete 
37c955072eca: Pull complete 
feab5319fb76: Pull complete 
b7a7b4a8603a: Pull complete 
f34770148620: Pull complete 
dd4dba888a87: Pull complete 
8ad8d914c867: Pull complete 
1fad2b6c7cf7: Pull complete 
```
